### ISSUE TITLE
EI35

### ISSUE THREAD

**Issue by hamidtb** [Nobtronix/PCBlib#1]
سلام

ممنون میشم اگه Step ترانس EI35 رو هم طراحی کنید
(ترانس پاور منابع تغذیه کامپیوتر)

12 پین
فاصله هر پین 5 میلیمتر
فاصله پین های ردیف اول و دوم 23 میلیمتر
![EI35](https://github.com/user-attachments/assets/9c083b8d-22eb-451a-ba3a-339fec20d233)

**Comment by Nobtronix** [comment]
سلام
 لطفا اگر دیتاشیتی از بوبین و هسته دارید بفرستید
Hi
Please send the datasheet for the bobbin and core if you have it.

> سلام
> 
> ممنون میشم اگه Step ترانس EI35 رو هم طراحی کنید (ترانس پاور منابع تغذیه کامپیوتر)
> 
> 12 پین فاصله هر پین 5 میلیمتر فاصله پین های ردیف اول و دوم 23 میلیمتر ![EI35](https://private-user-images.githubusercontent.com/5849217/371232426-9c083b8d-22eb-451a-ba3a-339fec20d233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MzI3MjIsIm5iZiI6MTcyNzYzMjQyMiwicGF0aCI6Ii81ODQ5MjE3LzM3MTIzMjQyNi05YzA4M2I4ZC0yMmViLTQ1MWEtYmEzYS0zMzlmZWMyMGQyMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjlUMTc1MzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmNlYTc0NmRmODQwNzI4MWQ3NmRiZjg2OTY2YTNlZGM5ZTU1Njg3NWU4M2MzNzVmYmFlMzA0N2Y1YjMyMjA5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.iKy1RIIKghJ0oGv7jOAvznI0iQk3YS4ugvXUbhtqJTE)

**Comment by hamidtb** [comment]
سلام، خدمت شما
[EI35](https://www.mycoiltech.com/6-6-pins-vertical-ei35-electronic-transformer-bobbin_p757.html)

**Comment by Nobtronix** [comment]
> سلام، خدمت شما [EI35](https://www.mycoiltech.com/6-6-pins-vertical-ei35-electronic-transformer-bobbin_p757.html)

فاصله پایه ها با عکس ارسالی متفاوت هستند اگر امکانش هست دوباره بررسی بفرمایید

The distance between the pins is different, if possible, please check again

**Comment by hamidtb** [comment]
سلام

ملاک دیتاشیتی هست که خدمتتون ارسال کردم؛ من چون ابعاد رو از روی یه ترانس کارکرده پاور کامپیوتر محاسبه کردم احتمال بروز خطا وجود داره
ممنونم

**Comment by Nobtronix** [comment]
سلام فوت پرینت EI35  به ریپو اضافه شد.

**Comment by hamidtb** [comment]
سلام، خیلی خیلی ممنونم
